"""
Weekly Reports route (Part 9, Tab 8 / Part 4.4). GET-only - reports are
generated by the nightly/weekly scheduled job (Part 8), never on request.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.api.deps import CurrentUser, get_current_user
from app.db.models import WeeklyReport
from app.db.session import get_db

router = APIRouter(prefix="/reports/weekly", tags=["weekly_reports"])


class WeeklyReportOut(BaseModel):
    id: str
    period_start: str
    period_end: str
    metrics_snapshot: dict
    narrative: str
    created_at: str


@router.get("", response_model=list[WeeklyReportOut])
def list_weekly_reports(
    current_user: CurrentUser = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> list[WeeklyReportOut]:
    rows = db.query(WeeklyReport).filter(
        WeeklyReport.organization_id == current_user.organization_id,
    ).order_by(WeeklyReport.period_end.desc()).all()

    return [
        WeeklyReportOut(
            id=r.id, period_start=r.period_start.isoformat(), period_end=r.period_end.isoformat(),
            metrics_snapshot=r.metrics_snapshot, narrative=r.narrative, created_at=r.created_at.isoformat(),
        )
        for r in rows
    ]


@router.get("/latest", response_model=WeeklyReportOut | None)
def get_latest_weekly_report(
    current_user: CurrentUser = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> WeeklyReportOut | None:
    r = db.query(WeeklyReport).filter(
        WeeklyReport.organization_id == current_user.organization_id,
    ).order_by(WeeklyReport.period_end.desc()).first()
    if r is None:
        return None
    return WeeklyReportOut(
        id=r.id, period_start=r.period_start.isoformat(), period_end=r.period_end.isoformat(),
        metrics_snapshot=r.metrics_snapshot, narrative=r.narrative, created_at=r.created_at.isoformat(),
    )
